Es 86
UST-DeMAF/opentelemetry-demo pull request #10
Opened 2024-09-27 13:32 UTC by eliasmueller

# Changes

Please provide a brief description of the changes here.

## Merge Requirements

For new features contributions, please make sure you have completed the following
essential items:

* [ ] `CHANGELOG.md` updated to document new feature additions
* [ ] Appropriate documentation updates in the [docs][]
* [ ] Appropriate Helm chart updates in the [helm-charts][]

Maintainers will not merge until the above have been completed. If you're unsure
which docs need to be changed ping the
[@open-telemetry/demo-approvers](https://github.com/orgs/open-telemetry/teams/demo-approvers).

[docs]: https://opentelemetry.io/docs/demo/
[helm-charts]: https://github.com/open-telemetry/opentelemetry-helm-charts

2024-09-27 15:39 UTC, eliasmueller commented on README.md
> +Lorem # TODO
noch nicht ganz fertig

2024-09-28 11:11 UTC, heidrifx requested changes
I'll mark this as _"request changes"_ to not accidentally push a docker image to our ghcr if we choose to change the naming

2024-09-28 11:11 UTC, heidrifx commented on README.md
> +In the [Terraform target model](./edmm/otel-store_terraform_translated.yaml), there are common component types for all docker_containers,
Personally, I would replace "docker_container" by either "docker container" or use Markdown code highlighting, i.e. `docker_container`

2024-09-28 11:11 UTC, heidrifx commented on README.md
> +Thus, all components obtain a _hosted_on_ relation.
- "hosted_on" was called "hosted-on" earlier, why change it here?
- same remark on "container_runtime" as with the "docker_container" in the other comment

2024-09-28 11:11 UTC, heidrifx commented on terraform/README.md
> +```
Correct me if I'm wrong but the `&&` will not work under Windows' CMD/Powershell
So maybe add a separate command hint for Windows?

2024-09-28 11:11 UTC, heidrifx commented on README.md
> +A usage guide can be found in the dedicated [README in /ansible](./ansible/README.md).
The README only has a command which will work on UNIX-like systems (i.e. MacOS and Linux) but calling `sudo` will most likely fail on Windows. Can we extend the README by a command which will work for Windows?

2024-09-28 11:11 UTC, heidrifx commented on .github/workflows/build-productcatalogservice-fork.yml
I have multiple remarks on this 😅:
- Why not use the workflow from our plugins as template?
  - i.e. QEMU is missing, action versions are not up-to-date
- Running the workflow on every push to main _and_ demaf will build images with the same tag thus overwriting the old one. So for example if the main branch works fine and someone pushes an incomplete version to demaf, the working docker image will _not_ be the latest one available.
  - In my opinion we should also use a _testing_ or _dev_ tag.
- Who is the `github.repository_owner` of this fork? Someone from the UST-DeMAF organization? If it is the original repository's owner maybe we should hardcode some one from our team?
- Did the arm64 version work locally?
- I find the usage of the `IMAGE_NAME` as suffix to the `IMAGE_TAG` kind of confusing. Why not simply extend the `IMAGE_TAG`?
- Lastly, I would change the image name from "demo" to "opentelemetry-demo" or "otel-demo". "demo" alone is a little confusing in my opinion as we also have other demos like the Kube example.

2024-09-28 11:11 UTC, heidrifx commented on kubernetes/opentelemetry-demo.yaml
> +          image: 'ghcr.io/ust-demaf/demo:1.11.1-productcatalogservice'
_If_ the workflow is changed this needs to be updated as well!

2024-09-28 11:31 UTC, eliasmueller commented on .github/workflows/build-productcatalogservice-fork.yml
Regarding the naming and tagging; I chose to use the exact same naming strategy as in the original repository, to be consistent, even though I agree it is kinda confusing;

Regarding the arm64, yes.

Regarding the owner, it is Marcel as it is forked into UST-DeMAF

Regarding the workflow -> yes I can adapt it to match the others

2024-09-29 06:48 UTC, eliasmueller commented on .github/workflows/build-productcatalogservice-fork.yml
adjusted the workflow to match the others

2024-09-29 15:14 UTC, heidrifx reviewed
lgtm but please take a last small look at the comment 😅

2024-09-29 15:14 UTC, heidrifx commented on .github/workflows/buildAndPushImage-productcatalogservice.yml
> +          submodules: 'true'
we are not using submodules for this, are we?
this does not hurt in any way but might be confusing

2024-09-30 05:49 UTC, merged